web_version/addon_items/urls.py
from django.urls import path
from . import views

app_name = 'addon_items'
urlpatterns = [
    path("", views.index, name='index'),
    path('add', views.add, name='add'),
    path('target', views.target, name='target'),
    path("<str:name>", views.greet, name='greet')
]

web_version/web_version/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('addon_items/', include('addon_items.urls'))
]

web_version/addon_items/models.py
from django.db import models

# Create your models here.

web_version/addon_items/views.py
from django import forms
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.http import require_http_methods

from pathlib import Path
import sys

MODULE_DIR = Path(__file__).resolve().parent.parent.parent
sys.path.append(str(MODULE_DIR))
from core import item, schedule


# Create your views here.

# global_items = [Item('apple', 5),
#                 Item('banana', 3),
#                 Item('tomato', 3)]

# items_cart = []
# total_target_price = None
# total_current_price = 0
scheduler = schedule.Scheduler(item.ItemCorpus())

def index(request):
    # return HttpResponse("Hello, world!\n <h1>This is add-on items!</h1>")
    # if 'items' not in request.session:
    #     request.session['items'] = []
    
    # request.session['items'].append(Item('apple', 5))
    # print('-' * 20)
    # print('global items:')
    # for item in request.session['items']:
    #     print(item)
    # print('-' * 20)

    # return render(request, 
    #               'addon_items/index.html',
    #               {
    #                 'items': request.session['items'],
    #                 'has_item': len(request.session['items']) > 0
    #               })

    #########################################################
    # items_cart
    # backup_items
    # target total price
    # current total price
    #########################################################
    backup_items = scheduler.recommend_items()
    item_cart = scheduler.item_cart
    target_total_price = scheduler.target_total_price
    current_total_price = scheduler.total_price

    return render(request,
                  'addon_items/index.html',
                  {
                    'item_cart': item_cart,
                    'backup_items': backup_items,
                    'has_backup_item': len(backup_items) > 0,
                    'target_total_price': target_total_price,
                    'current_total_price': current_total_price
                  })

@require_http_methods(['POST'])
def add(request):
    item_name = request.POST.get('item_name', '')
    item_price = request.POST.get('item_price', '')

    new_item = item.Item(item_name, float(item_price))
    scheduler.add_item(new_item)

    # log
    print('#' * 20)
    print(f"new item: {str(new_item)}")
    print('#' * 20)

    return HttpResponseRedirect(reverse("addon_items:index"))

@require_http_methods(['POST'])
def target(request):
    target_total_price = request.POST.get('target_price', '')
    scheduler.set_target_total_price(float(target_total_price))

    # log
    print('#' * 20)
    print(f'Target total price: {target_total_price}')
    print('#' * 20)

    return HttpResponseRedirect(reverse("addon_items:index"))

def greet(request, name):
    # return HttpResponse(f"<h1>Hello, {name}</h1>\n Welcome to <b>Add-on Items!</b>")
    return render(request,
                  'addon_items/welcome.html',
                  {
                      'name': name.capitalize()
                  })

web_version/addon_items/templates/addon_items/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>
            Add-on Items Homepage
        </title>
        <link href="{% static 'addon_items/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <header>
            Welcome to the homepage of <b>Add-on Items</b> 
        </header>

        <form action="{% url 'addon_items:target' %}" method="post">
            {% csrf_token %}
            <div>
                Current target total price: {{ target_total_price }}
            </div>

            <div>
                <label>
                    Set target price:
                </label>
                <input autofocus="autofocus" name="target_price" type="text" />
                <input value="Update" type="submit" />
            </div>

        </form>

        <form action="{% url 'addon_items:add' %}" method="post">
            {% csrf_token %}
            <div>
                <label>
                    The new item name:
                </label>
                <input autofocus="autofocus" name="item_name" type="text" />
            </div>
            <div>
                <label>
                    The new item price:
                </label>
                <input autofocus="autofocus" name="item_price" type="text" />
            </div>
            <div>
                <input value="Add the item to cart" type="submit" />
            </div>
        </form>

        <div class="backup_items">
            <p>
                Backup items: 
            </p>
            {% if has_backup_item %}
                <ul>
                    {% for item in backup_items %}
                        <li>Item name: {{ item.name }}; item price: {{ item.price }}</li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>
                    No recommendation item yet.
                </p>
            {% endif %}
        </div>

        <div class="item_cart">
            <p>
                Current item cart:
            </p>
            <ul>
                {% for item in item_cart %}
                    <li>Item name: {{ item.name }}; item price: {{ item.price }}</li>
                {% endfor %}
            </ul>

            <p>
                Current total price in cart: {{ current_total_price }}
            </p>
        </div>
    </body>
</html>

web_version/addon_items/templates/addon_items/welcome.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>
            Welcome
        </title>
    </head>
    <body>
        <p>
            Welcome {{ name }} to <b>Add-on Items</b>!
        </p>
    </body>
</html>